name: Commit to Master Branch
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  extract:
    if: |
      !contains(github.event.head_commit.message, '[actions]')
    runs-on:
      - self-hosted
      - java
    outputs:
      major: ${{ steps.major.outputs.major }}
      minor: ${{ steps.step2.outputs.minor }}
      patch: ${{ steps.step2.outputs.patch }}
    steps:
      - uses: actions/checkout@v3
      - id: major
        run: |
          ::set-output name=major::$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.majorVersion -q -DforceStdout)
      - id: minor
        run: |
          ::set-output name=minor::$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.minorVersion -q -DforceStdout)
      - id: patch
        run: |
          ::set-output name=patch::$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.incrementalVersion -q -DforceStdout)
  echo-version:
    runs-on: ubuntu-latest
    needs: extract
    steps:
      - run: echo ${{needs.extract.outputs.major}}.${{needs.extract.outputs.minor}}.${{needs.extract.outputs.patch}}
          
