name: Commit to Master Branch
on:
  push:
    branches:
      - "master"

jobs:
  test:
    if: |
      !contains(github.event.head_commit.message, '[actions]')
    uses: rcsb/devops-test-cicd-java/.github/workflows/run-tests.yaml@master
#TODO integration tests
  extract:
    name: extract-version
    needs: test
    runs-on:
      - self-hosted
      - java
    outputs:
      major: ${{ steps.major.outputs.major }}
      minor: ${{ steps.minor.outputs.minor }}
      patch: ${{ steps.patch.outputs.patch }}
    steps:
      - uses: actions/checkout@v3
      - id: major
        run: |
          echo ::set-output name=major::$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.majorVersion -q -DforceStdout --no-transfer-progress)
      - id: minor
        run: |
          echo ::set-output name=minor::$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.minorVersion -q -DforceStdout --no-transfer-progress)
      - id: patch
        run: |
          echo ::set-output name=patch::$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.incrementalVersion -q -DforceStdout --no-transfer-progress)
  echo-version:
    runs-on: ubuntu-latest
    needs: extract
    steps:
      - run: echo ${{needs.extract.outputs.major}}.${{needs.extract.outputs.minor}}.${{needs.extract.outputs.patch}}
  dispatch-update-version:
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Update Version
#          workflow: .github/workflows/update-version.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            { 
              "major": "${{needs.extract.outputs.major}}", 
              "minor": "${{needs.extract.outputs.minor}}", 
              "patch": "${{needs.extract.outputs.patch}}"
            }