name: Push to Branch

on:
  push:
    branches-ignore:
      - "master"

jobs:
  test:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/run-tests.yaml@master
  dispatch-build-and-push-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Build and Push Docker
          #          workflow: .github/workflows/update-version.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            { 
              "tag": "${{ github.ref_name }}"
            }