name: Push to Branch

on:
  push:
    branches-ignore:
      - "master"
  workflow_call: {}

jobs:
  test:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/run-tests.yaml@master
  call-build-and-push-docker:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/build-and-push-docker.yaml@master
    with:
      tag: "${{ github.ref_name }}"