name: Release

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major version'
        required: true
      minor:
        description: 'Minor version'
        required: true
      patch:
        description: 'Patch version'
        required: true
      skip-tests:
        description: 'Skip tests'
        type: boolean
        default: true
        required: false
      distribution:
        description: 'buildlocker distribution name'
        required: true
  workflow_call: {}

jobs:
  run-tests:
    if: "!${{ github.event.inputs.skip-tests }}"
    uses: rcsb/devops-cicd-github-actions/.github/workflows/run-tests.yaml@master
  call-update-version:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/update-version.yaml@master
  call-build-and-push-docker:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/build-and-push-docker.yaml@master
    with:
      tag: "${{github.event.inputs.major}}.${{github.event.inputs.minor}}.${{github.event.inputs.patch}}"
  call-deploy-to-buildloker:
    needs:
      - call-build-and-push-docker
    uses: rcsb/devops-cicd-github-actions/.github/workflows/deploy-to-buildloker.yaml@RO3686
    with:
      distribution: "${{github.event.inputs.distribution}}"