name: Release

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major version'
        required: true
      minor:
        description: 'Minor version'
        required: true
      patch:
        description: 'Patch version'
        required: true
      skip-tests:
        description: 'Skip tests'
        type: boolean
        default: true
        required: false
      namespace:
        description: 'K8s target namespaces'
        default: "production"
        required: false

jobs:
  run-tests:
    if: "!${{ github.event.inputs.skip-tests }}"
    uses: rcsb/devops-cicd-github-actions/.github/workflows/run-tests.yaml@master
  call-update-version:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/update-version.yaml@master
  call-build-and-push-docker:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/build-and-push-docker.yaml@master
    with:
      tag: "${{github.event.inputs.major}}.${{github.event.inputs.minor}}.${{github.event.inputs.patch}}"
  call-skaffold-deploy-staging:
    needs:
      - call-build-and-push-docker
    uses: rcsb/devops-cicd-github-actions/.github/workflows/skaffold-deploy.yaml@master
    with:
      tag: "${{github.event.inputs.major}}.${{github.event.inputs.minor}}.${{github.event.inputs.patch}}"
      namespace: "staging"
  dispatch-integration-tests:
    needs:
      - call-skaffold-deploy-staging
    runs-on: ubuntu-latest
    steps:
      - run: test true
  call-skaffold-deploy-production:
    needs:
      - dispatch-integration-tests
    uses: rcsb/devops-cicd-github-actions/.github/workflows/skaffold-deploy.yaml@master
    with:
      tag: "${{github.event.inputs.major}}.${{github.event.inputs.minor}}.${{github.event.inputs.patch}}"
      namespace: "${{ github.event.inputs.namespace}}"