name: Run After Commit
on:
  workflow_run:
    workflows: [ "Commit to Branch" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  after-commit:
    if: |
      contains(github.event.head_commit.message, '[test]')
    runs-on:
      - self-hosted
      - java
    steps:
      - name: Check file
        run: |
          cat testfile.txt
