name: Update Version

on:
  workflow_call:
    inputs:
      major:
        description: 'Schema Major version'
        required: true
      minor:
        description: 'Schema Minor version'
        required: true
      patch:
        description: 'Schema Patch version'
        required: true


env:
  NEW_SCHEMA_VERSION: "${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}"

jobs:
  update-version:
    runs-on:
      - self-hosted
      - java
    steps:
      - uses: actions/checkout@v3
      - name: Setup git author information
        run: |
          git config user.name RCSBSystem
          git config user.email it@rcsb.org
      - run: mvn --version
      - name: Set new schema dependency version
        run: |
          mvn versions:set-property -Dproperty=rcsb.mojave.model.version -DnewVersion=$NEW_SCHEMA_VERSION -DgenerateBackupPoms=false
      - name: Commit and tag
        run: |
          git add pom.xml
          git commit -m "[actions] Updated schema dependency version to $NEW_SCHEMA_VERSION"
      - name: Push back to GitHub
        run: git push --all
